name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: summary
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          repositories: 200          
          repositories_affiliations: owner, collaborator
          config_timezone: Europe/Madrid
          filename: summary.svg
      - name: activity & community
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: activity, community
          repositories: 200                 
          repositories_affiliations: owner, collaborator
          config_timezone: Europe/Madrid
          filename: activity-community.svg
      - name: repositories
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          repositories: 200           
          repositories_affiliations: owner, collaborator
          config_timezone: Europe/Madrid
          filename: repositories.svg
          plugin_lines: yes
