name: Metrics
on:
  schedule: [{cron: "0 0 * * 0"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
     - name: header
       uses: lowlighter/metrics@latest
       with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          repositories: 200          
          repositories_affiliations: owner, collaborator
          config_timezone: Europe/Madrid
          filename: header.svg
          use_prebuilt_image: yes
     - name: activity & community
       uses: lowlighter/metrics@latest
       with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: activity, community
          repositories: 200                 
          repositories_affiliations: owner, collaborator
          config_timezone: Europe/Madrid
          filename: activity-community.svg
          use_prebuilt_image: yes
     - name: repositories
       uses: lowlighter/metrics@latest
       with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          repositories: 200           
          repositories_affiliations: owner, collaborator
          config_timezone: Europe/Madrid
          filename: repositories.svg
          use_prebuilt_image: yes
          plugin_lines: yes
     - name: plugin reactions
       uses: lowlighter/metrics@latest
       with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          repositories: 200           
          repositories_affiliations: owner, collaborator
          config_timezone: Europe/Madrid
          filename: reactions.svg
          use_prebuilt_image: yes
          plugin_reactions: yes
          plugin_reactions_limit: 200
          plugin_reactions_days: 30
          plugin_reactions_details: count, percentage
     - name: plugin topics
       uses: lowlighter/metrics@latest
       with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          repositories: 200           
          repositories_affiliations: owner, collaborator
          config_timezone: Europe/Madrid
          filename: topics.svg
          use_prebuilt_image: yes
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_mode: mastered
          plugin_topics_limit: 20
#     - name: plugin achievements
#       uses: lowlighter/metrics@latest
#       with:
#          token: ${{ secrets.METRICS_TOKEN }}
#          base: ""
#          repositories: 200           
#          repositories_affiliations: owner, collaborator
#          config_timezone: Europe/Madrid
#          filename: achievements.svg
#          use_prebuilt_image: yes
#          plugin_achievements: yes
#          plugin_achievements_threshold: B
#          plugin_achievements_secrets: yes
#          plugin_achievements_limit: 0
     - name: plugin followup
       uses: lowlighter/metrics@latest
       with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          repositories: 200           
          repositories_affiliations: owner, collaborator
          config_timezone: Europe/Madrid
          filename: followup.svg
          use_prebuilt_image: yes
          plugin_followup: yes
     - name: plugin stackoverflow
       uses: lowlighter/metrics@latest
       with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          repositories: 200           
          repositories_affiliations: owner, collaborator
          config_timezone: Europe/Madrid
          filename: stackoverflow.svg
          use_prebuilt_image: yes
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 3086403                           
          plugin_stackoverflow_sections: ""
          plugin_stackoverflow_limit: 2                                
          plugin_stackoverflow_lines: 4  
     - name: plugin posts
       uses: lowlighter/metrics@latest
       with:
          token: NOT_NEEDED
          base: ""
          config_timezone: Europe/Madrid
          filename: posts.svg
          use_prebuilt_image: yes                             
          plugin_posts: yes
          plugin_posts_covers: yes
          plugin_posts_descriptions: yes
          plugin_posts_source: dev.to
          plugin_people_user: .github.user
     - name: plugin stargazers chart
       uses: lowlighter/metrics@latest
       with:
         filename: stargazers.svg
         token: ${{ secrets.METRICS_TOKEN }}
         base: ""
         plugin_stargazers: yes
         plugin_stargazers_charts_type: graph
         plugin_stargazers_days: 0
     - name: MBTI Personality profile
       uses: lowlighter/metrics@latest
       with:
         filename: 16personalities.svg
         token: ${{ secrets.METRICS_TOKEN }}
         base: ""
         plugin_16personalities: yes
         plugin_16personalities_url: ${{ secrets.SIXTEEN_PERSONALITIES_URL }}
         plugin_16personalities_sections: personality, traits
         plugin_16personalities_scores: no
