name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: summary
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          repositories: 200          
          repositories_affiliations: owner, collaborator
          config_timezone: Europe/Madrid
          filename: summary.svg
      - name: activity & community
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: activity, community
          repositories: 200                 
          repositories_affiliations: owner, collaborator
          config_timezone: Europe/Madrid
          filename: activity-community.svg
      - name: repositories
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          repositories: 200           
          repositories_affiliations: owner, collaborator
          config_timezone: Europe/Madrid
          filename: repositories.svg
          plugin_lines: yes
      - name: plugin topics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          repositories: 200
          repositories_affiliations: owner, collaborator
          config_timezone: Europe/Madrid
          filename: topics.svg
          use_prebuilt_image: yes
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_mode: mastered
          plugin_topics_limit: 20
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
      - name: plugin achievements
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          repositories: 200
          repositories_affiliations: owner, collaborator
          config_timezone: Europe/Madrid
          filename: achievements.svg
          use_prebuilt_image: yes
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 0